--
-- Create DB schema
--

CREATE TABLE user (
  id INTEGER NOT NULL IDENTITY,
  login VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  UNIQUE (login)
)

CREATE TABLE article (
  id INTEGER NOT NULL IDENTITY,
  title VARCHAR(100) NOT NULL,
  lead VARCHAR(1000) NOT NULL,
  text VARCHAR(10000) NOT NULL
)

CREATE TABLE comment (
  id INTEGER GENERATED ALWAYS AS IDENTITY,
  text VARCHAR(100) NOT NULL,
  article_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL
)